---  
spring: 
  datasource: 
    name: mydb  
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/atcrrowdfunding180416
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis: 
  mapperLocations: classpath*:/mybatis/mapper-*.xml
  typeAliasesPackage: com.atguigu.**.bean
